In [1]:
import csv

In [2]:
import numpy as np

In [3]:
data=[]
with open (r"C:\Users\admin\Downloads\SampleTemperature Sheet - mysheet.csv",'r') as csvfile:
    reader=csv.reader(csvfile,delimiter=',')
    for row in reader:
        data.append(row)
data=np.array(data)

1.Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [4]:
data

array([['Temprature Sheet', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
       ['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['', 'Week 1', '10', '27', '12', '22', '15', '21', '15', '26',
        '8', '32', '11', '28', '8', '32'],
       ['', 'Week 2', '11', '27', '14', '21', '12', '32', '-13', '29',
        '14', '21', '7', '24', '7', '21'],
       ['', 'Week 3', '7', '31', '11', '20', '6', '26', '6', '20', '14',
        '25', '6', '22', '9', '21'],
       ['', 'Week 4', '6', '26', '15', '26', '7', '23', '9', '31', '11',
        '24', '10', '23', '14', '22'],
       ['December', 'Week 1', '1

In [5]:
data[4:8,0]='November'

In [6]:
data[9:12,0]='December'

In [7]:
data[13:16,0]='January'

In [8]:
data[17:20,0]='February'

In [9]:
data[2,3]='Monday'

In [10]:
data[2,5]='Tuesday'

In [11]:
data[2,7]='Wednesday'

In [12]:
data[2,9]='Thursday'

In [13]:
data[2,11]='Friday'

In [14]:
data[2,13]='Saturday'

In [15]:
data[2,15]='Sunday'

In [63]:
data=np.delete(data,0,axis=0)

In [65]:
data=np.delete(data,0,axis=0)

In [66]:
data

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '10', '27', '12', '22', '15', '21', '15',
        '26', '8', '32', '11', '28', '8', '32'],
       ['November', 'Week 2', '11', '27', '14', '21', '12', '32', '-13',
        '29', '14', '21', '7', '24', '7', '21'],
       ['November', 'Week 3', '7', '31', '11', '20', '6', '26', '6',
        '20', '14', '25', '6', '22', '9', '21'],
       ['November', 'Week 4', '6', '26', '15', '26', '7', '23', '9',
        '31', '11', '24', '10', '23', '14', '22'],
       ['December', 'Week 1', '10', '25', '6', '27', '11', '29', '13',
        '21', '12', '24', '7', '25', '12'

2.Write the dimensions and shape of the NumPy array that you have
created.

In [67]:
data.ndim

2

In [68]:
data.shape

(18, 16)

3.Print the daily temperatures for the first week of each month.

In [72]:
a=np.array(data[::4,0:])

In [73]:
a

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', 'Week 3', '7', '31', '11', '20', '6', '26', '6',
        '20', '14', '25', '6', '22', '9', '21'],
       ['December', 'Week 3', '8', '32', '6', '32', '11', '20', '13',
        '20', '11', '29', '12', '32', '11', '32'],
       ['January', 'Week 3', '2', '22', '6', '19', '2', '20', '4', '18',
        '2', '22', '6', '6', '21', '4'],
       ['February', 'Week 3', '12', '19', '9', '19', '8', '21', '12',
        '19', '10', '22', '12', '9', '20', '9']], dtype='<U16')

4.Print the temperatures for Tuesday of each month.


In [74]:
tuesday=data[0:,4:6]

In [76]:
month=data[0:,0:2]

In [77]:
np.hstack((month,tuesday))

array([['Month', 'Week', 'Tuesday', 'Tuesday'],
       ['November', '', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '12', '22'],
       ['November', 'Week 2', '14', '21'],
       ['November', 'Week 3', '11', '20'],
       ['November', 'Week 4', '15', '26'],
       ['December', 'Week 1', '6', '27'],
       ['December', 'Week 2', '7', '26'],
       ['December', 'Week 3', '6', '32'],
       ['December', 'Week 4', '12', '23'],
       ['January', 'Week 1', '7', '19'],
       ['January', 'Week 2', '4', '20'],
       ['January', 'Week 3', '6', '19'],
       ['January', 'Week 4', '8', '21'],
       ['February', 'Week 1', '9', '22'],
       ['February', 'Week 2', '7', '22'],
       ['February', 'Week 3', '9', '19'],
       ['February', 'Week 4', '10', '22']], dtype='<U16')

5.Print only the maximum temperature for all the weekdays of Dec and Feb.

In [79]:
Dec_temp=data[6:10,3::2]

In [80]:
Dec_temp

array([['25', '27', '29', '21', '24', '25', '22'],
       ['31', '26', '23', '20', '23', '21', '31'],
       ['32', '32', '20', '20', '29', '32', '32'],
       ['20', '23', '28', '31', '32', '22', '26']], dtype='<U16')

In [81]:
Feb_temp=data[14:,3::2]

In [82]:
Feb_temp

array([['22', '22', '19', '21', '22', '71', '10'],
       ['18', '22', '18', '18', '20', '12', '9'],
       ['19', '19', '21', '19', '22', '9', '9'],
       ['21', '22', '21', '19', '22', '8', '11']], dtype='<U16')

In [103]:
dec_and_feb_temp=np.vstack(((data[0,3::2],Dec_temp,Feb_temp)))

In [104]:
dec=data[6:10,0:2]

In [95]:
dec

array([['December', 'Week 1'],
       ['December', 'Week 2'],
       ['December', 'Week 3'],
       ['December', 'Week 4']], dtype='<U16')

In [96]:
feb=data[14:,0:2]

In [97]:
feb

array([['February', 'Week 1'],
       ['February', 'Week 2'],
       ['February', 'Week 3'],
       ['February', 'Week 4']], dtype='<U16')

In [105]:
dec_feb=np.vstack(((data[0,0:2],dec,feb)))

In [106]:
dec_feb

array([['Month', 'Week'],
       ['December', 'Week 1'],
       ['December', 'Week 2'],
       ['December', 'Week 3'],
       ['December', 'Week 4'],
       ['February', 'Week 1'],
       ['February', 'Week 2'],
       ['February', 'Week 3'],
       ['February', 'Week 4']], dtype='<U16')

In [107]:
dec_and_feb_max_temp=np.hstack((dec_feb,dec_and_feb_temp))

In [108]:
dec_and_feb_max_temp

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['December', 'Week 1', '25', '27', '29', '21', '24', '25', '22'],
       ['December', 'Week 2', '31', '26', '23', '20', '23', '21', '31'],
       ['December', 'Week 3', '32', '32', '20', '20', '29', '32', '32'],
       ['December', 'Week 4', '20', '23', '28', '31', '32', '22', '26'],
       ['February', 'Week 1', '22', '22', '19', '21', '22', '71', '10'],
       ['February', 'Week 2', '18', '22', '18', '18', '20', '12', '9'],
       ['February', 'Week 3', '19', '19', '21', '19', '22', '9', '9'],
       ['February', 'Week 4', '21', '22', '21', '19', '22', '8', '11']],
      dtype='<U16')

6.Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees. 

In [112]:
min_temp_1=data[2:,0:]

In [117]:
nov_temp=min_temp_1[0:4,2::2]

In [118]:
nov_temp

array([['10', '12', '15', '15', '8', '11', '8'],
       ['11', '14', '12', '-13', '14', '7', '7'],
       ['7', '11', '6', '6', '14', '6', '9'],
       ['6', '15', '7', '9', '11', '10', '14']], dtype='<U16')

In [119]:
nov_temp.shape

(4, 7)

In [123]:
nov=nov_temp.reshape(4*7,)

In [124]:
nov1=nov.astype(int)

In [125]:
nov1

array([ 10,  12,  15,  15,   8,  11,   8,  11,  14,  12, -13,  14,   7,
         7,   7,  11,   6,   6,  14,   6,   9,   6,  15,   7,   9,  11,
        10,  14])

In [126]:
h1=[]
for i in nov1:
    if i<8:
        h1.append(i)
    else:
        h1.append('')
print(h1)

['', '', '', '', '', '', '', '', '', '', -13, '', 7, 7, 7, '', 6, 6, '', 6, '', 6, '', 7, '', '', '', '']


In [128]:
h1=np.array(h1)

In [129]:
min_temp_2=h1.reshape(4,7)

In [130]:
min_temp_2

array([['', '', '', '', '', '', ''],
       ['', '', '', '-13', '', '7', '7'],
       ['7', '', '6', '6', '', '6', ''],
       ['6', '', '7', '', '', '', '']], dtype='<U11')

In [142]:
days_for_nov=data[0,2::2]

In [143]:
min_of_nov=np.vstack((days_for_nov,min_temp_2))

In [144]:
min_of_nov

array([['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        'Saturday', 'Sunday'],
       ['', '', '', '', '', '', ''],
       ['', '', '', '-13', '', '7', '7'],
       ['7', '', '6', '6', '', '6', ''],
       ['6', '', '7', '', '', '', '']], dtype='<U16')

In [145]:
weeks_for_nov=data[0:6,0:2]

In [146]:
weeks_for_nov

array([['Month', 'Week'],
       ['November', ''],
       ['November', 'Week 1'],
       ['November', 'Week 2'],
       ['November', 'Week 3'],
       ['November', 'Week 4']], dtype='<U16')

In [149]:
weeks_for_nov_1=np.delete(weeks_for_nov,1,axis=0)

In [150]:
np.hstack((weeks_for_nov_1,min_of_nov))

array([['Month', 'Week', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
        'Friday', 'Saturday', 'Sunday'],
       ['November', 'Week 1', '', '', '', '', '', '', ''],
       ['November', 'Week 2', '', '', '', '-13', '', '7', '7'],
       ['November', 'Week 3', '7', '', '6', '6', '', '6', ''],
       ['November', 'Week 4', '6', '', '7', '', '', '', '']], dtype='<U16')

7.Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.

In [151]:
dec_jan=data[6:14]

In [152]:
dec_jan

array([['December', 'Week 1', '10', '25', '6', '27', '11', '29', '13',
        '21', '12', '24', '7', '25', '12', '22'],
       ['December', 'Week 2', '7', '31', '7', '26', '10', '23', '11',
        '20', '10', '23', '9', '21', '13', '31'],
       ['December', 'Week 3', '8', '32', '6', '32', '11', '20', '13',
        '20', '11', '29', '12', '32', '11', '32'],
       ['December', 'Week 4', '6', '20', '12', '23', '12', '28', '13',
        '31', '7', '32', '15', '22', '7', '26'],
       ['January', 'Week 1', '5', '19', '7', '19', '4', '21', '7', '21',
        '5', '22', '2', '7', '18', '4'],
       ['January', 'Week 2', '5', '22', '4', '20', '6', '21', '3', '21',
        '7', '19', '6', '6', '18', '8'],
       ['January', 'Week 3', '2', '22', '6', '19', '2', '20', '4', '18',
        '2', '22', '6', '6', '21', '4'],
       ['January', 'Week 4', '7', '19', '8', '21', '4', '19', '8', '21',
        '7', '18', '2', '8', '18', '5']], dtype='<U16')

In [153]:
dec_to_jan=dec_jan[0:,2:].astype(int)

In [154]:
dec_to_jan

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [155]:
dec_to_jan.shape

(8, 14)

In [156]:
dec_to_jan_temp=dec_to_jan.reshape(8*14)

In [157]:
dec_to_jan_temp

array([10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22,  7, 31,  7,
       26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31,  8, 32,  6, 32, 11, 20,
       13, 20, 11, 29, 12, 32, 11, 32,  6, 20, 12, 23, 12, 28, 13, 31,  7,
       32, 15, 22,  7, 26,  5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7,
       18,  4,  5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8,  2,
       22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4,  7, 19,  8, 21,
        4, 19,  8, 21,  7, 18,  2,  8, 18,  5])

In [158]:
d1=[]
for j in dec_to_jan_temp:
    if j>20:
        d1.append(j)
    else:
        d1.append('')
print(d1)


['', 25, '', 27, '', 29, '', 21, '', 24, '', 25, '', 22, '', 31, '', 26, '', 23, '', '', '', 23, '', 21, '', 31, '', 32, '', 32, '', '', '', '', '', 29, '', 32, '', 32, '', '', '', 23, '', 28, '', 31, '', 32, '', 22, '', 26, '', '', '', '', '', 21, '', 21, '', 22, '', '', '', '', '', 22, '', '', '', 21, '', 21, '', '', '', '', '', '', '', 22, '', '', '', '', '', '', '', 22, '', '', 21, '', '', '', '', 21, '', '', '', 21, '', '', '', '', '', '']


In [161]:
d1=np.array(d1).reshape(8,14)

In [162]:
np.hstack((dec_jan[0:,0:2],d1))

array([['December', 'Week 1', '', '25', '', '27', '', '29', '', '21', '',
        '24', '', '25', '', '22'],
       ['December', 'Week 2', '', '31', '', '26', '', '23', '', '', '',
        '23', '', '21', '', '31'],
       ['December', 'Week 3', '', '32', '', '32', '', '', '', '', '',
        '29', '', '32', '', '32'],
       ['December', 'Week 4', '', '', '', '23', '', '28', '', '31', '',
        '32', '', '22', '', '26'],
       ['January', 'Week 1', '', '', '', '', '', '21', '', '21', '',
        '22', '', '', '', ''],
       ['January', 'Week 2', '', '22', '', '', '', '21', '', '21', '',
        '', '', '', '', ''],
       ['January', 'Week 3', '', '22', '', '', '', '', '', '', '', '22',
        '', '', '21', ''],
       ['January', 'Week 4', '', '', '', '21', '', '', '', '21', '', '',
        '', '', '', '']], dtype='<U16')

8.Check if there are any absurd values present in the dataset(like some temp
which should not be present in the data)

In [164]:
cond=data[2:,:]

In [165]:
cond_1=cond==''

In [166]:
cond[cond_1]

array([], dtype='<U16')

9. What strategy would you use to handle such data points?

10. Find and print the indexes of all the outlier(unusual) values present in
the above dataset.

In [210]:
temp_all=data[2:,2:].astype(int)

In [213]:
temp_all.shape

(16, 14)

In [216]:
np.where(temp_all<0)

(array([ 1, 12], dtype=int64), array([6, 4], dtype=int64))

11.Replace the outliers with an appropriate value.

In [214]:
over_all=temp_all.reshape(16*14)

In [215]:
over_all

array([ 10,  27,  12,  22,  15,  21,  15,  26,   8,  32,  11,  28,   8,
        32,  11,  27,  14,  21,  12,  32, -13,  29,  14,  21,   7,  24,
         7,  21,   7,  31,  11,  20,   6,  26,   6,  20,  14,  25,   6,
        22,   9,  21,   6,  26,  15,  26,   7,  23,   9,  31,  11,  24,
        10,  23,  14,  22,  10,  25,   6,  27,  11,  29,  13,  21,  12,
        24,   7,  25,  12,  22,   7,  31,   7,  26,  10,  23,  11,  20,
        10,  23,   9,  21,  13,  31,   8,  32,   6,  32,  11,  20,  13,
        20,  11,  29,  12,  32,  11,  32,   6,  20,  12,  23,  12,  28,
        13,  31,   7,  32,  15,  22,   7,  26,   5,  19,   7,  19,   4,
        21,   7,  21,   5,  22,   2,   7,  18,   4,   5,  22,   4,  20,
         6,  21,   3,  21,   7,  19,   6,   6,  18,   8,   2,  22,   6,
        19,   2,  20,   4,  18,   2,  22,   6,   6,  21,   4,   7,  19,
         8,  21,   4,  19,   8,  21,   7,  18,   2,   8,  18,   5,   9,
        22,   9,  22, -10,  19,   9,  21,   8,  22,  12,  71,  1

In [217]:
k1=[]
for t in over_all:
    if t<0:
        k1.append('10.10')
    else:
        k1.append(t)
print(k1)

[10, 27, 12, 22, 15, 21, 15, 26, 8, 32, 11, 28, 8, 32, 11, 27, 14, 21, 12, 32, '10.10', 29, 14, 21, 7, 24, 7, 21, 7, 31, 11, 20, 6, 26, 6, 20, 14, 25, 6, 22, 9, 21, 6, 26, 15, 26, 7, 23, 9, 31, 11, 24, 10, 23, 14, 22, 10, 25, 6, 27, 11, 29, 13, 21, 12, 24, 7, 25, 12, 22, 7, 31, 7, 26, 10, 23, 11, 20, 10, 23, 9, 21, 13, 31, 8, 32, 6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32, 6, 20, 12, 23, 12, 28, 13, 31, 7, 32, 15, 22, 7, 26, 5, 19, 7, 19, 4, 21, 7, 21, 5, 22, 2, 7, 18, 4, 5, 22, 4, 20, 6, 21, 3, 21, 7, 19, 6, 6, 18, 8, 2, 22, 6, 19, 2, 20, 4, 18, 2, 22, 6, 6, 21, 4, 7, 19, 8, 21, 4, 19, 8, 21, 7, 18, 2, 8, 18, 5, 9, 22, 9, 22, '10.10', 19, 9, 21, 8, 22, 12, 71, 18, 10, 11, 18, 7, 22, 10, 18, 12, 18, 7, 20, 11, 12, 21, 9, 12, 19, 9, 19, 8, 21, 12, 19, 10, 22, 12, 9, 20, 9, 7, 21, 10, 22, 8, 21, 7, 19, 11, 22, 9, 8, 20, 11]


In [220]:
k1=np.array(k1).reshape(16,14)

In [221]:
k1

array([['10', '27', '12', '22', '15', '21', '15', '26', '8', '32', '11',
        '28', '8', '32'],
       ['11', '27', '14', '21', '12', '32', '10.10', '29', '14', '21',
        '7', '24', '7', '21'],
       ['7', '31', '11', '20', '6', '26', '6', '20', '14', '25', '6',
        '22', '9', '21'],
       ['6', '26', '15', '26', '7', '23', '9', '31', '11', '24', '10',
        '23', '14', '22'],
       ['10', '25', '6', '27', '11', '29', '13', '21', '12', '24', '7',
        '25', '12', '22'],
       ['7', '31', '7', '26', '10', '23', '11', '20', '10', '23', '9',
        '21', '13', '31'],
       ['8', '32', '6', '32', '11', '20', '13', '20', '11', '29', '12',
        '32', '11', '32'],
       ['6', '20', '12', '23', '12', '28', '13', '31', '7', '32', '15',
        '22', '7', '26'],
       ['5', '19', '7', '19', '4', '21', '7', '21', '5', '22', '2', '7',
        '18', '4'],
       ['5', '22', '4', '20', '6', '21', '3', '21', '7', '19', '6', '6',
        '18', '8'],
       ['2', '22', '6', '

12.Find the average max temperature for the winter months in Jaipur.

In [167]:
winter_avg=data[2:14,3::2].astype(int)

In [170]:
winter_avg
# average of nov,dec and jan

array([[27, 22, 21, 26, 32, 28, 32],
       [27, 21, 32, 29, 21, 24, 21],
       [31, 20, 26, 20, 25, 22, 21],
       [26, 26, 23, 31, 24, 23, 22],
       [25, 27, 29, 21, 24, 25, 22],
       [31, 26, 23, 20, 23, 21, 31],
       [32, 32, 20, 20, 29, 32, 32],
       [20, 23, 28, 31, 32, 22, 26],
       [19, 19, 21, 21, 22,  7,  4],
       [22, 20, 21, 21, 19,  6,  8],
       [22, 19, 20, 18, 22,  6,  4],
       [19, 21, 19, 21, 18,  8,  5]])

In [171]:
np.average(winter_avg)

22.404761904761905

13.Find the weekly min avg temp for the month of Dec in Jaipur


In [51]:
min_avg=data[8:12,2::2].astype(int)

In [52]:
min_avg

array([[10,  6, 11, 13, 12,  7, 12],
       [ 7,  7, 10, 11, 10,  9, 13],
       [ 8,  6, 11, 13, 11, 12, 11],
       [ 6, 12, 12, 13,  7, 15,  7]])

In [183]:
week_1=min_avg[0]
w1=np.mean(week_1)
w1

10.142857142857142

In [184]:
week_2=min_avg[1]
w2=np.mean(week_2)
w2

9.571428571428571

In [185]:
week_3=min_avg[2]
w3=np.mean(week_3)
w3

10.285714285714286

In [186]:
week_4=min_avg[3]
w4=np.mean(week_4)
w4

10.285714285714286

In [189]:
arr=np.array([w1,w2,w3,w4])

In [191]:
np.mean(arr)

10.071428571428571

14.Find the overall avg temp for the months Dec and Jan

In [192]:
dec_to_jan

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [193]:
np.average(dec_to_jan)

14.776785714285714

15.Find the least temp experienced by the city in the month of Dec and
Jan. Also print the exact date( Day/Week/Month) for the same.

In [194]:
dec_to_jan

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [195]:
dec_to_jan.min()

2

In [196]:
dec_to_jan.shape

(8, 14)

In [197]:
dec_to_jan_1=dec_to_jan.reshape(8*14,)

In [199]:
f1=[]
for r in dec_to_jan_1:
    if r==2:
        f1.append(r)
    else:
        f1.append('')
print(f1)

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2, '', '', '', 2, '', '', '', 2, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 2, '', '', '']


In [200]:
f1=np.array(f1).reshape(8,14)

In [202]:
f2=np.hstack((dec_jan[0:,0:2],f1))

In [204]:
np.vstack((data[0],f2))

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['December', 'Week 1', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['December', 'Week 2', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['December', 'Week 3', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['December', 'Week 4', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['January', 'Week 1', '', '', '', '', '', '', '', '', '', '', '2',
        '', '', ''],
       ['January', 'Week 2', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['January', 'Week 3', '2', '', '', '', '2', '', '', '', '2', '',
        '', '', '', ''],
       ['January', 'Week 4', '', '', '', '', '', '', '', '', '', '', '2',
        '', '', '']], dtype='<U16')

16. Find the max temp in the month of Feb and return its
date(Day/Week/Month)

In [224]:
temp_feb=data[14:,2:].astype(int)

In [229]:
temp_feb.max()

71

In [226]:
temp_feb.shape

(4, 14)

In [227]:
temp_max_feb=temp_feb.reshape(4*14,)

In [228]:
temp_max_feb

array([  9,  22,   9,  22, -10,  19,   9,  21,   8,  22,  12,  71,  18,
        10,  11,  18,   7,  22,  10,  18,  12,  18,   7,  20,  11,  12,
        21,   9,  12,  19,   9,  19,   8,  21,  12,  19,  10,  22,  12,
         9,  20,   9,   7,  21,  10,  22,   8,  21,   7,  19,  11,  22,
         9,   8,  20,  11])

In [230]:
l1=[]
for y in temp_max_feb:
    if y==71:
        l1.append(y)
    else:
        l1.append('')
print(l1)

['', '', '', '', '', '', '', '', '', '', '', 71, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']


In [232]:
l1=np.array(l1).reshape(4,14)

In [233]:
l2=np.hstack((data[14:,0:2],l1))

In [234]:
l2

array([['February', 'Week 1', '', '', '', '', '', '', '', '', '', '', '',
        '71', '', ''],
       ['February', 'Week 2', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['February', 'Week 3', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['February', 'Week 4', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '']], dtype='<U16')

In [235]:
np.vstack((data[0],l2))

array([['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['February', 'Week 1', '', '', '', '', '', '', '', '', '', '', '',
        '71', '', ''],
       ['February', 'Week 2', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['February', 'Week 3', '', '', '', '', '', '', '', '', '', '', '',
        '', '', ''],
       ['February', 'Week 4', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '']], dtype='<U16')

19.The above data is appropriate for an audience who follow the metric
system of measurement. Create an array that holds the same data but
presented in Fahrenheit.

In [205]:
e=data[2:,2:].astype(int)

In [206]:
e

array([[ 10,  27,  12,  22,  15,  21,  15,  26,   8,  32,  11,  28,   8,
         32],
       [ 11,  27,  14,  21,  12,  32, -13,  29,  14,  21,   7,  24,   7,
         21],
       [  7,  31,  11,  20,   6,  26,   6,  20,  14,  25,   6,  22,   9,
         21],
       [  6,  26,  15,  26,   7,  23,   9,  31,  11,  24,  10,  23,  14,
         22],
       [ 10,  25,   6,  27,  11,  29,  13,  21,  12,  24,   7,  25,  12,
         22],
       [  7,  31,   7,  26,  10,  23,  11,  20,  10,  23,   9,  21,  13,
         31],
       [  8,  32,   6,  32,  11,  20,  13,  20,  11,  29,  12,  32,  11,
         32],
       [  6,  20,  12,  23,  12,  28,  13,  31,   7,  32,  15,  22,   7,
         26],
       [  5,  19,   7,  19,   4,  21,   7,  21,   5,  22,   2,   7,  18,
          4],
       [  5,  22,   4,  20,   6,  21,   3,  21,   7,  19,   6,   6,  18,
          8],
       [  2,  22,   6,  19,   2,  20,   4,  18,   2,  22,   6,   6,  21,
          4],
       [  7,  19,   8,  21,   4,  19,   8, 

In [207]:
(e*(9/5)+32)

array([[ 50. ,  80.6,  53.6,  71.6,  59. ,  69.8,  59. ,  78.8,  46.4,
         89.6,  51.8,  82.4,  46.4,  89.6],
       [ 51.8,  80.6,  57.2,  69.8,  53.6,  89.6,   8.6,  84.2,  57.2,
         69.8,  44.6,  75.2,  44.6,  69.8],
       [ 44.6,  87.8,  51.8,  68. ,  42.8,  78.8,  42.8,  68. ,  57.2,
         77. ,  42.8,  71.6,  48.2,  69.8],
       [ 42.8,  78.8,  59. ,  78.8,  44.6,  73.4,  48.2,  87.8,  51.8,
         75.2,  50. ,  73.4,  57.2,  71.6],
       [ 50. ,  77. ,  42.8,  80.6,  51.8,  84.2,  55.4,  69.8,  53.6,
         75.2,  44.6,  77. ,  53.6,  71.6],
       [ 44.6,  87.8,  44.6,  78.8,  50. ,  73.4,  51.8,  68. ,  50. ,
         73.4,  48.2,  69.8,  55.4,  87.8],
       [ 46.4,  89.6,  42.8,  89.6,  51.8,  68. ,  55.4,  68. ,  51.8,
         84.2,  53.6,  89.6,  51.8,  89.6],
       [ 42.8,  68. ,  53.6,  73.4,  53.6,  82.4,  55.4,  87.8,  44.6,
         89.6,  59. ,  71.6,  44.6,  78.8],
       [ 41. ,  66.2,  44.6,  66.2,  39.2,  69.8,  44.6,  69.8,  41. ,
         