In [1]:
import numpy as np

In [2]:
a=np.linspace(10,25,9).reshape(3,3)

In [3]:
a

array([[10.   , 11.875, 13.75 ],
       [15.625, 17.5  , 19.375],
       [21.25 , 23.125, 25.   ]])

In [4]:
b=np.array([[1],[2],[3]])

In [5]:
b

array([[1],
       [2],
       [3]])

In [7]:
np.append(a,b,axis=1)

array([[10.   , 11.875, 13.75 ,  1.   ],
       [15.625, 17.5  , 19.375,  2.   ],
       [21.25 , 23.125, 25.   ,  3.   ]])