In [1]:
import numpy as np

In [4]:
a=np.arange(1,10).reshape(3,3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b=np.linspace(5,15,9).reshape(3,3)

In [10]:
b

array([[ 5.  ,  6.25,  7.5 ],
       [ 8.75, 10.  , 11.25],
       [12.5 , 13.75, 15.  ]])

In [18]:
np.dot(a,b)

array([[ 60.  ,  67.5 ,  75.  ],
       [138.75, 157.5 , 176.25],
       [217.5 , 247.5 , 277.5 ]])