In [1]:
import csv

In [2]:
import numpy as np

In [3]:
data=[]
with open (r"C:\Users\admin\Downloads\SampleTemperature Sheet - mysheet.csv",'r') as csvfile:
    reader=csv.reader(csvfile,delimiter=',')
    for row in reader:
        data.append(row)
data=np.array(data)

1.Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.


In [4]:
data

array([['Temprature Sheet', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
       ['Month', 'Week', 'Monday', '', 'Tuesday', '', 'Wednesday', '',
        'Thursday', '', 'Friday', '', 'Saturday', '', 'Sunday', ''],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['', 'Week 1', '10', '27', '12', '22', '15', '21', '15', '26',
        '8', '32', '11', '28', '8', '32'],
       ['', 'Week 2', '11', '27', '14', '21', '12', '32', '-13', '29',
        '14', '21', '7', '24', '7', '21'],
       ['', 'Week 3', '7', '31', '11', '20', '6', '26', '6', '20', '14',
        '25', '6', '22', '9', '21'],
       ['', 'Week 4', '6', '26', '15', '26', '7', '23', '9', '31', '11',
        '24', '10', '23', '14', '22'],
       ['December', 'Week 1', '1

In [5]:
data[4:8,0]='November'

In [6]:
data[9:12,0]='December'

In [7]:
data[13:16,0]='January'

In [8]:
data[17:20,0]='February'

In [9]:
data[2,3]='Monday'

In [10]:
data[2,5]='Tuesday'

In [11]:
data[2,7]='Wednesday'

In [12]:
data[2,9]='Thursday'

In [13]:
data[2,11]='Friday'

In [14]:
data[2,13]='Saturday'

In [15]:
data[2,15]='Sunday'

In [16]:
data

array([['Temprature Sheet', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
       ['Month', 'Week', 'Monday', 'Monday', 'Tuesday', 'Tuesday',
        'Wednesday', 'Wednesday', 'Thursday', 'Thursday', 'Friday',
        'Friday', 'Saturday', 'Saturday', 'Sunday', 'Sunday'],
       ['November', '', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp',
        'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp',
        'Max Temp', 'Min Temp', 'Max Temp', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '10', '27', '12', '22', '15', '21', '15',
        '26', '8', '32', '11', '28', '8', '32'],
       ['November', 'Week 2', '11', '27', '14', '21', '12', '32', '-13',
        '29', '14', '21', '7', '24', '7', '21'],
       ['November', 'Week 3', '7', '31', '11', '20', '6', '26', '6',
        '20', '14', '25', '6', '22', '9', '21'],
       ['November', 'Week 4', '6', '26', '15', '26', '7', '23'

2.Write the dimensions and shape of the NumPy array that you have
created.

In [17]:
data.ndim

2

In [18]:
data.shape

(20, 16)

3.Print the daily temperatures for the first week of each month.

In [19]:
a=np.array(data[4::4,0:])

In [20]:
a

array([['November', 'Week 1', '10', '27', '12', '22', '15', '21', '15',
        '26', '8', '32', '11', '28', '8', '32'],
       ['December', 'Week 1', '10', '25', '6', '27', '11', '29', '13',
        '21', '12', '24', '7', '25', '12', '22'],
       ['January', 'Week 1', '5', '19', '7', '19', '4', '21', '7', '21',
        '5', '22', '2', '7', '18', '4'],
       ['February', 'Week 1', '9', '22', '9', '22', '-10', '19', '9',
        '21', '8', '22', '12', '71', '18', '10']], dtype='<U16')

4.Print the temperatures for Tuesday of each month.


In [21]:
tuesday_temp=data[3:,4:6]

In [22]:
month=data[3:,0:2]

In [23]:
np.hstack((month,tuesday_temp))

array([['November', '', 'Min Temp', 'Max Temp'],
       ['November', 'Week 1', '12', '22'],
       ['November', 'Week 2', '14', '21'],
       ['November', 'Week 3', '11', '20'],
       ['November', 'Week 4', '15', '26'],
       ['December', 'Week 1', '6', '27'],
       ['December', 'Week 2', '7', '26'],
       ['December', 'Week 3', '6', '32'],
       ['December', 'Week 4', '12', '23'],
       ['January', 'Week 1', '7', '19'],
       ['January', 'Week 2', '4', '20'],
       ['January', 'Week 3', '6', '19'],
       ['January', 'Week 4', '8', '21'],
       ['February', 'Week 1', '9', '22'],
       ['February', 'Week 2', '7', '22'],
       ['February', 'Week 3', '9', '19'],
       ['February', 'Week 4', '10', '22']], dtype='<U16')

5.Print only the maximum temperature for all the weekdays of Dec and Feb.

In [24]:
Dec_to_Feb=data[8:16,3::2]

In [25]:
Dec_to_Feb_month=data[8:16,0:2]

In [26]:
Dec_to_Feb_month

array([['December', 'Week 1'],
       ['December', 'Week 2'],
       ['December', 'Week 3'],
       ['December', 'Week 4'],
       ['January', 'Week 1'],
       ['January', 'Week 2'],
       ['January', 'Week 3'],
       ['January', 'Week 4']], dtype='<U16')

In [27]:
np.hstack((Dec_to_Feb_month,Dec_to_Feb))

array([['December', 'Week 1', '25', '27', '29', '21', '24', '25', '22'],
       ['December', 'Week 2', '31', '26', '23', '20', '23', '21', '31'],
       ['December', 'Week 3', '32', '32', '20', '20', '29', '32', '32'],
       ['December', 'Week 4', '20', '23', '28', '31', '32', '22', '26'],
       ['January', 'Week 1', '19', '19', '21', '21', '22', '7', '4'],
       ['January', 'Week 2', '22', '20', '21', '21', '19', '6', '8'],
       ['January', 'Week 3', '22', '19', '20', '18', '22', '6', '4'],
       ['January', 'Week 4', '19', '21', '19', '21', '18', '8', '5']],
      dtype='<U16')

6.Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees. 

In [28]:
min_temp_1=data[2:,2::2]

In [29]:
min_temp_1

array([['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday',
        'Saturday', 'Sunday'],
       ['Min Temp', 'Min Temp', 'Min Temp', 'Min Temp', 'Min Temp',
        'Min Temp', 'Min Temp'],
       ['10', '12', '15', '15', '8', '11', '8'],
       ['11', '14', '12', '-13', '14', '7', '7'],
       ['7', '11', '6', '6', '14', '6', '9'],
       ['6', '15', '7', '9', '11', '10', '14'],
       ['10', '6', '11', '13', '12', '7', '12'],
       ['7', '7', '10', '11', '10', '9', '13'],
       ['8', '6', '11', '13', '11', '12', '11'],
       ['6', '12', '12', '13', '7', '15', '7'],
       ['5', '7', '4', '7', '5', '2', '18'],
       ['5', '4', '6', '3', '7', '6', '18'],
       ['2', '6', '2', '4', '2', '6', '21'],
       ['7', '8', '4', '8', '7', '2', '18'],
       ['9', '9', '-10', '9', '8', '12', '18'],
       ['11', '7', '10', '12', '7', '11', '21'],
       ['12', '9', '8', '12', '10', '12', '20'],
       ['7', '10', '8', '7', '11', '9', '20']], dtype='<U16')

In [30]:
min_temp_2=data[5:8,0:2]

In [31]:
min_temp_2

array([['November', 'Week 2'],
       ['November', 'Week 3'],
       ['November', 'Week 4']], dtype='<U16')

In [32]:
b=(min_temp_1[2:6].astype(int))

In [33]:
np.where(b<8)

(array([1, 1, 1, 2, 2, 2, 2, 3, 3], dtype=int64),
 array([3, 5, 6, 0, 2, 3, 5, 0, 2], dtype=int64))

In [34]:
b

array([[ 10,  12,  15,  15,   8,  11,   8],
       [ 11,  14,  12, -13,  14,   7,   7],
       [  7,  11,   6,   6,  14,   6,   9],
       [  6,  15,   7,   9,  11,  10,  14]])

In [35]:
c=np.array([[b[1,3],b[1,5],b[1,6]],[b[2,0],b[2,2],b[2,3]],[b[3,0],b[3,2],0]])

In [36]:
np.hstack((min_temp_2,c))

array([['November', 'Week 2', '-13', '7', '7'],
       ['November', 'Week 3', '7', '6', '6'],
       ['November', 'Week 4', '6', '7', '0']], dtype='<U16')

7.Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.

In [37]:
f=data[8:16]

In [38]:
f

array([['December', 'Week 1', '10', '25', '6', '27', '11', '29', '13',
        '21', '12', '24', '7', '25', '12', '22'],
       ['December', 'Week 2', '7', '31', '7', '26', '10', '23', '11',
        '20', '10', '23', '9', '21', '13', '31'],
       ['December', 'Week 3', '8', '32', '6', '32', '11', '20', '13',
        '20', '11', '29', '12', '32', '11', '32'],
       ['December', 'Week 4', '6', '20', '12', '23', '12', '28', '13',
        '31', '7', '32', '15', '22', '7', '26'],
       ['January', 'Week 1', '5', '19', '7', '19', '4', '21', '7', '21',
        '5', '22', '2', '7', '18', '4'],
       ['January', 'Week 2', '5', '22', '4', '20', '6', '21', '3', '21',
        '7', '19', '6', '6', '18', '8'],
       ['January', 'Week 3', '2', '22', '6', '19', '2', '20', '4', '18',
        '2', '22', '6', '6', '21', '4'],
       ['January', 'Week 4', '7', '19', '8', '21', '4', '19', '8', '21',
        '7', '18', '2', '8', '18', '5']], dtype='<U16')

In [39]:
d=data[8:16:,2:].astype(int)

In [40]:
d

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [41]:
np.where(d>20)

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7], dtype=int64),
 array([ 1,  3,  5,  7,  9, 11, 13,  1,  3,  5,  9, 11, 13,  1,  3,  9, 11,
        13,  3,  5,  7,  9, 11, 13,  5,  7,  9,  1,  5,  7,  1,  9, 12,  3,
         7], dtype=int64))

In [42]:
max_temp=np.array([[d[0,1],d[0,3],d[0,5],d[0,7],d[0,9],d[0,11],d[0,13]],[d[1,1],d[1,3],d[1,5],d[1,9],d[1,11],d[1,13],0],
                   [d[2,1],d[2,3],d[2,9],d[2,11],d[2,13],0,0],[d[3,3],d[3,5],d[3,7],d[3,9],d[3,11],d[3,13],0],
                   [d[4,5],d[4,7],d[4,9],0,0,0,0],
                   [d[5,1],d[5,5],d[5,7],0,0,0,0],[d[6,1],d[6,9],d[6,12],0,0,0,0],[d[7,3],d[7,7],0,0,0,0,0]])

In [43]:
max_temp

array([[25, 27, 29, 21, 24, 25, 22],
       [31, 26, 23, 23, 21, 31,  0],
       [32, 32, 29, 32, 32,  0,  0],
       [23, 28, 31, 32, 22, 26,  0],
       [21, 21, 22,  0,  0,  0,  0],
       [22, 21, 21,  0,  0,  0,  0],
       [22, 22, 21,  0,  0,  0,  0],
       [21, 21,  0,  0,  0,  0,  0]])

In [44]:
e=data[8:16,0:2]

In [45]:
e

array([['December', 'Week 1'],
       ['December', 'Week 2'],
       ['December', 'Week 3'],
       ['December', 'Week 4'],
       ['January', 'Week 1'],
       ['January', 'Week 2'],
       ['January', 'Week 3'],
       ['January', 'Week 4']], dtype='<U16')

In [46]:
np.hstack((e,max_temp))

array([['December', 'Week 1', '25', '27', '29', '21', '24', '25', '22'],
       ['December', 'Week 2', '31', '26', '23', '23', '21', '31', '0'],
       ['December', 'Week 3', '32', '32', '29', '32', '32', '0', '0'],
       ['December', 'Week 4', '23', '28', '31', '32', '22', '26', '0'],
       ['January', 'Week 1', '21', '21', '22', '0', '0', '0', '0'],
       ['January', 'Week 2', '22', '21', '21', '0', '0', '0', '0'],
       ['January', 'Week 3', '22', '22', '21', '0', '0', '0', '0'],
       ['January', 'Week 4', '21', '21', '0', '0', '0', '0', '0']],
      dtype='<U16')

8.Check if there are any absurd values present in the dataset(like some temp
which should not be present in the data)

In [47]:
data[4:,0:]==''

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, Fals

12.Find the average max temperature for the winter months in Jaipur.

In [48]:
winter_avg=data[4:16,3::2].astype(int)

In [49]:
winter_avg

array([[27, 22, 21, 26, 32, 28, 32],
       [27, 21, 32, 29, 21, 24, 21],
       [31, 20, 26, 20, 25, 22, 21],
       [26, 26, 23, 31, 24, 23, 22],
       [25, 27, 29, 21, 24, 25, 22],
       [31, 26, 23, 20, 23, 21, 31],
       [32, 32, 20, 20, 29, 32, 32],
       [20, 23, 28, 31, 32, 22, 26],
       [19, 19, 21, 21, 22,  7,  4],
       [22, 20, 21, 21, 19,  6,  8],
       [22, 19, 20, 18, 22,  6,  4],
       [19, 21, 19, 21, 18,  8,  5]])

In [50]:
np.average(winter_avg)

22.404761904761905

13.Find the weekly min avg temp for the month of Dec in Jaipur


In [51]:
min_avg=data[8:12,2::2].astype(int)

In [52]:
min_avg

array([[10,  6, 11, 13, 12,  7, 12],
       [ 7,  7, 10, 11, 10,  9, 13],
       [ 8,  6, 11, 13, 11, 12, 11],
       [ 6, 12, 12, 13,  7, 15,  7]])

In [53]:
np.average(min_avg)

10.071428571428571

14.Find the overall avg temp for the months Dec and Jan

In [54]:
d

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [55]:
np.average(d)

14.776785714285714

15.Find the least temp experienced by the city in the month of Dec and
Jan. Also print the exact date( Day/Week/Month) for the same.

In [56]:
d

array([[10, 25,  6, 27, 11, 29, 13, 21, 12, 24,  7, 25, 12, 22],
       [ 7, 31,  7, 26, 10, 23, 11, 20, 10, 23,  9, 21, 13, 31],
       [ 8, 32,  6, 32, 11, 20, 13, 20, 11, 29, 12, 32, 11, 32],
       [ 6, 20, 12, 23, 12, 28, 13, 31,  7, 32, 15, 22,  7, 26],
       [ 5, 19,  7, 19,  4, 21,  7, 21,  5, 22,  2,  7, 18,  4],
       [ 5, 22,  4, 20,  6, 21,  3, 21,  7, 19,  6,  6, 18,  8],
       [ 2, 22,  6, 19,  2, 20,  4, 18,  2, 22,  6,  6, 21,  4],
       [ 7, 19,  8, 21,  4, 19,  8, 21,  7, 18,  2,  8, 18,  5]])

In [57]:
d.min()

2

In [58]:
np.where(f=='2')

(array([4, 6, 6, 6, 7], dtype=int64), array([12,  2,  6, 10, 12], dtype=int64))

19.The above data is appropriate for an audience who follow the metric
system of measurement. Create an array that holds the same data but
presented in Fahrenheit.

In [61]:
e=data[4:,2:].astype(int)

In [62]:
e

array([[ 10,  27,  12,  22,  15,  21,  15,  26,   8,  32,  11,  28,   8,
         32],
       [ 11,  27,  14,  21,  12,  32, -13,  29,  14,  21,   7,  24,   7,
         21],
       [  7,  31,  11,  20,   6,  26,   6,  20,  14,  25,   6,  22,   9,
         21],
       [  6,  26,  15,  26,   7,  23,   9,  31,  11,  24,  10,  23,  14,
         22],
       [ 10,  25,   6,  27,  11,  29,  13,  21,  12,  24,   7,  25,  12,
         22],
       [  7,  31,   7,  26,  10,  23,  11,  20,  10,  23,   9,  21,  13,
         31],
       [  8,  32,   6,  32,  11,  20,  13,  20,  11,  29,  12,  32,  11,
         32],
       [  6,  20,  12,  23,  12,  28,  13,  31,   7,  32,  15,  22,   7,
         26],
       [  5,  19,   7,  19,   4,  21,   7,  21,   5,  22,   2,   7,  18,
          4],
       [  5,  22,   4,  20,   6,  21,   3,  21,   7,  19,   6,   6,  18,
          8],
       [  2,  22,   6,  19,   2,  20,   4,  18,   2,  22,   6,   6,  21,
          4],
       [  7,  19,   8,  21,   4,  19,   8, 

In [66]:
(e*(9/5)+32)

array([[ 50. ,  80.6,  53.6,  71.6,  59. ,  69.8,  59. ,  78.8,  46.4,
         89.6,  51.8,  82.4,  46.4,  89.6],
       [ 51.8,  80.6,  57.2,  69.8,  53.6,  89.6,   8.6,  84.2,  57.2,
         69.8,  44.6,  75.2,  44.6,  69.8],
       [ 44.6,  87.8,  51.8,  68. ,  42.8,  78.8,  42.8,  68. ,  57.2,
         77. ,  42.8,  71.6,  48.2,  69.8],
       [ 42.8,  78.8,  59. ,  78.8,  44.6,  73.4,  48.2,  87.8,  51.8,
         75.2,  50. ,  73.4,  57.2,  71.6],
       [ 50. ,  77. ,  42.8,  80.6,  51.8,  84.2,  55.4,  69.8,  53.6,
         75.2,  44.6,  77. ,  53.6,  71.6],
       [ 44.6,  87.8,  44.6,  78.8,  50. ,  73.4,  51.8,  68. ,  50. ,
         73.4,  48.2,  69.8,  55.4,  87.8],
       [ 46.4,  89.6,  42.8,  89.6,  51.8,  68. ,  55.4,  68. ,  51.8,
         84.2,  53.6,  89.6,  51.8,  89.6],
       [ 42.8,  68. ,  53.6,  73.4,  53.6,  82.4,  55.4,  87.8,  44.6,
         89.6,  59. ,  71.6,  44.6,  78.8],
       [ 41. ,  66.2,  44.6,  66.2,  39.2,  69.8,  44.6,  69.8,  41. ,
         