In [1]:
import numpy as np

In [5]:
a=np.random.randint(23,37,9)

In [7]:
b=a.reshape(3,3)

In [8]:
b

array([[32, 32, 31],
       [32, 29, 35],
       [34, 26, 26]])

In [21]:
b[::-1]

array([[34, 26, 26],
       [32, 29, 35],
       [32, 32, 31]])

In [22]:
c=np.random.randint(2,15,9).reshape(3,3)

In [23]:
c

array([[ 4,  4, 10],
       [13, 14,  2],
       [13,  6, 11]])

In [24]:
b*c

array([[128, 128, 310],
       [416, 406,  70],
       [442, 156, 286]])