In [1]:
import numpy as np

In [3]:
sample_array=np.array([[34,43,73],[82,22,12],[53,94,66]])


In [4]:
sample_array

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [13]:
np.max(sample_array,axis=0)

array([82, 94, 73])

In [14]:
np.min(sample_array,axis=1)

array([34, 12, 53])