In [1]:
import numpy as np

In [3]:
sample_array=np.array([[34,43,73],[82,22,12],[53,94,66]])


In [4]:
sample_array

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [6]:
newcolumn = np.array([[10,10,10]])


In [10]:
a=np.delete(sample_array,1,axis=1)

In [11]:
a

array([[34, 73],
       [82, 12],
       [53, 66]])

In [18]:
np.insert(a,1,newcolumn,axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])