In [1]:
import numpy as np


In [9]:
a=np.arange(2,14,2)

In [16]:
b=a.reshape(2,3)

In [20]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
c=np.random.randint(5,30,6).reshape(2,3)

In [18]:
c

array([[ 9, 11, 14],
       [17, 13,  8]])

In [19]:
b*c

array([[ 18,  44,  84],
       [136, 130,  96]])