In [1]:
import numpy as np

In [5]:
a=np.random.randint(5,15,9).reshape(3,3)

In [6]:
a

array([[12, 14, 13],
       [10,  8,  9],
       [ 5, 11, 10]])

In [7]:
b=np.arange(2,11).reshape(3,3)

In [8]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
#addition
a+b

array([[14, 17, 17],
       [15, 14, 16],
       [13, 20, 20]])

In [10]:
#substraction
a-b

array([[10, 11,  9],
       [ 5,  2,  2],
       [-3,  2,  0]])

In [11]:
#product
a*b

array([[ 24,  42,  52],
       [ 50,  48,  63],
       [ 40,  99, 100]])

In [12]:
#Division
a/b

array([[6.        , 4.66666667, 3.25      ],
       [2.        , 1.33333333, 1.28571429],
       [0.625     , 1.22222222, 1.        ]])