In [1]:
import numpy as np

In [5]:
a=np.array([0,1,2,3,4,5,6])

In [12]:
#Original array
a

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
b=np.ones(7)

In [10]:
for i in b:
    b[b==i]=3

In [11]:
b

array([3., 3., 3., 3., 3., 3., 3.])

In [15]:
#First array elements raised to powers from second array,
a**b

array([  0.,   1.,   8.,  27.,  64., 125., 216.])