In [1]:
import numpy as np

In [3]:
a=np.random.randint(2,18,15).reshape(5,3)

In [4]:
a

array([[16,  7, 11],
       [ 6, 17, 11],
       [13,  4, 14],
       [ 7,  2, 14],
       [ 8, 11,  4]])

In [12]:
b=np.arange(2,8,1).reshape(3,2)

In [13]:
b

array([[2, 3],
       [4, 5],
       [6, 7]])

In [14]:
np.matmul(a,b)

array([[126, 160],
       [146, 180],
       [126, 157],
       [106, 129],
       [ 84, 107]])