In [18]:
import numpy as np

In [21]:
a=np.random.randint(23,35,4).reshape(2,2)

In [22]:
a

array([[32, 26],
       [33, 34]])

In [24]:
#sort along 1st axis
np.sort(a,axis=0)

array([[32, 26],
       [33, 34]])

In [27]:
#Sort along last axis
np.sort(a)

array([[26, 32],
       [33, 34]])

In [30]:
a.flatten()

array([32, 26, 33, 34])