In [1]:
import numpy as np

In [4]:
a=np.arange(25,50).reshape(5,5)

In [5]:
a

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [27]:
#sum of rows

In [28]:
np.sum(a,axis=1)

array([135, 160, 185, 210, 235])

In [29]:
#sum of coloumns
np.sum(a,axis=0)

array([175, 180, 185, 190, 195])

In [30]:
#sum of all elements
np.sum(a)

925